// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yteuptbygfdwzrocmjot.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl0ZXVwdGJ5Z2Zkd3pyb2Ntam90Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4MjM1MTcsImV4cCI6MjA2MTM5OTUxN30.q1nmVUV51eTMuM0GeaBr2KBHTMwWa-3uANcNwSb-qLY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);